Byttet funksjonene expect_*(f(), NA) til expect_no_*(f))
Rapporteket/rapwhale pull request #14
Opened 2023-10-19 07:37 UTC by orjanls

2023-10-20 12:17 UTC, haugedal requested changes
Ser bra ut 👍

I linje 39 i `test-anonymiser.R`, som me såg litt på tidlegare, var truleg `NA` plassert feil i utgangspunktet. `NA` skulle nok vore i `expect_error()` og ikkje `suppressWarnings()`. Me kan gjerne berre retta det med ein gong, altså byta til `expect_no_error()` og fjerna `NA`.

2023-10-23 11:09 UTC, orjanls commented
Nå er linje 39 i  `test-anonymiser.R` oppdatert til expect_no_error().

2023-10-23 11:47 UTC, haugedal commented
👍

Loggmeldinga i siste commit bør forklara at testen var implementert feil før (feilplassert `NA`). Bruk det ekstra avsnittet i loggmeldinga for ekstra detaljar når du treng meir enn éi linje.

Du kan enkelt oppdatera den siste loggmeldinga ved å køyra `git commit --amend` (og så `git push --force-with-lease`).

2023-10-23 12:48 UTC, haugedal approved these changes

2023-10-23 12:51 UTC, merged