Oppdatert scoped verbs *_at()
Rapporteket/rapwhale pull request #25
Opened 2023-11-10 15:10 UTC by orjanls

Oppdaterte *_at() til *(across()) som vist [her](https://dplyr.tidyverse.org/reference/mutate_all.html). 
I filen 'dformat-checkware.R' er det i tillegg lagt til 'stopifnot()' på validering av kodebok, og dato for innlesing av kodebok.
'variabel_id_checkware' er forandret til å inkludere 'skjema_id' og fyller inn kanonisk.

2023-11-13 13:56 UTC, haugedal requested changes
Har lagt inn kommentarar direkte i kodelinjene i filene. Det meste går på utdaterte (superseded) ting og kodestil.

Og så bør me kanskje få avklart om me skal bruka `\(x)` for anonyme funksjonar, eller om `~` òg er greitt.

2023-11-13 13:56 UTC, haugedal commented on R/dformat-checkware.R
> +    mutate(across(dato_kl_var, ~ readr::parse_datetime(.x, format = "%Y-%m-%d %H:%M:%S")))
Har me bestemt noko om bruken av anonyme funksjonar (`\(x)` vs. `~`), @statkarl?

2023-11-13 13:56 UTC, haugedal commented on R/dformat-checkware.R
> +    mutate(across(boolsk_var, ~ cw_til_boolsk))
Her må det eventuelt stå `~ cw_til_boolsk(.)`, men me kan droppa heile `~`, då `cw_til_boolsk` allereie er ein funksjon.

2023-11-13 13:56 UTC, haugedal commented on R/dformat-mrs.R
> +    mutate(across(boolske_var, ~ mrs_boolsk_til_boolsk))
Fjern `~`.

2023-11-13 13:56 UTC, haugedal commented on R/datadump-valider.R
> +            across(c(foo = !!varnamn),
Her bør det vel stå `all_of(varnamn)` i staden for `c(foo = !!varnamn)`? Gjeld fleire tilsvarande plassar i fila.

2023-11-13 13:56 UTC, haugedal commented on R/dformat-checkware.R
> +    mutate(across(dato_kl_var, ~ readr::parse_datetime(.x, format = "%Y-%m-%d %H:%M:%S")))
Alle plassar me gjer inn ein vektor med kolonnenamn til `across()` skal me bruka `all_of()` eller `any_of()`. Gjeld fleire plassar.

2023-11-13 13:56 UTC, haugedal commented on R/dformat-oqr.R
> +    ))
Pass på rett innrykk (bruk `styler`). Bruk og argumentnamnet `.fns` på andre argument i `across()`, då kan `vars_datokl` (`all_of(vars_datokl)`) stå på same linje som `across(`. Eventuelt må du bruka argumentnamn her òg (`.cols`), viss det skal stå på ei eiga linje.

2023-11-13 13:56 UTC, haugedal commented on R/dformat-checkware.R
> +    mutate(across(boolsk_var, ~ cw_til_boolsk))
Bruk `all_of()`.

2023-11-13 13:56 UTC, haugedal commented on R/dformat-mrs.R
> +    mutate(across(boolske_var, ~ mrs_boolsk_til_boolsk))
Bruk `all_of()`.

2023-11-13 13:56 UTC, haugedal commented on R/dformat-mrs.R
> +    mutate(across(tid_var, ~ readr::parse_datetime(.x, format = "%d.%m.%Y %H:%M:%S")))
Bruk `all_of()`.

2023-11-13 13:56 UTC, haugedal commented on R/dformat-oqr.R
> +    mutate(across(vars_num, as.numeric))
Bruk `all_of()`, og `!!`.

2023-11-13 13:56 UTC, haugedal commented on R/dformat-oqr.R
> +    mutate(across(vars_boolsk, oqr_boolsk_til_boolsk))
Bruk `all_of()`, og `!!`.

2023-11-13 13:56 UTC, haugedal commented on R/dformat-oqr.R
> +      vars_datokl,
Bruk `all_of()`, og `!!`.

2023-11-13 13:56 UTC, haugedal commented on R/datadump-valider.R
> +            across(c(foo = !!varnamn),
Bruk `all_of()`.

2023-11-13 13:56 UTC, haugedal commented on R/datadump-valider.R
> +            across(c(foo = !!varnamn),
Bruk `all_of()`.

2023-11-13 13:56 UTC, haugedal commented on R/datadump-valider.R
> +            across(c(foo = !!varnamn),
Bruk `all_of()`.

2023-11-13 13:56 UTC, haugedal commented on R/datadump-valider.R
> +            across(c(foo = !!varnamn),
Bruk `all_of()`.

2023-11-13 13:56 UTC, haugedal commented on R/datadump-valider.R
> +            across(c(foo = !!varnamn),
Bruk `all_of()`.

2023-11-13 13:56 UTC, haugedal commented on R/datadump-valider.R
> +            across(c(foo = !!varnamn),
Bruk `all_of()`.

2023-11-13 13:56 UTC, haugedal commented on R/datadump-valider.R
> +            across(c(foo = !!varnamn),
Bruk `all_of()`.

2023-11-13 13:56 UTC, haugedal commented on R/les_dd_oqr_csv.R
> +        .x,
Sett `.x,` på same linje som `konverter_boolske(`. Viss han skal stå på ei eiga linje skal argumentnamnet brukast (`x = .x,`).

2023-11-13 13:56 UTC, haugedal commented on R/les_dd_oqr_csv.R
> +        )
Flytt eventuelt `d, across(all_of(` på same linje som `mutate(`, og bruk argumentnamn `.fns` for den anonyme funksjonen.

2023-11-13 13:56 UTC, haugedal commented on R/les_dd_oqr_csv.R
> +      ~ konverter_boolske(
Flytt eventuelt `d, across(all_of(` på same linje som `mutate(`, og bruk argumentnamn `.fns` for den anonyme funksjonen.

2023-11-13 13:56 UTC, haugedal commented on R/les_kb_v2.R
> +    ~ konverter_tekst(.x,
Flytt eventuelt `across(all_of(` til linja over, og bruk argumentnamn `.fns` for den anonyme funksjonen.

2023-11-13 13:56 UTC, haugedal commented on R/les_kb_v2.R
> +    ~ konverter_tekst(.x,
Flytt eventuelt `across(all_of(` til linja over, og bruk argumentnamn `.fns` for den anonyme funksjonen.

2023-11-13 13:56 UTC, haugedal commented on R/les_kb_v2.R
> +    ~ konverter_tekst(.x,
Flytt eventuelt `across(all_of(` til linja over, og bruk argumentnamn `.fns` for den anonyme funksjonen.

2023-11-13 13:56 UTC, haugedal commented on R/rapwhale-package.R
>  #' @importFrom dplyr vars
Denne kan òg fjernast.

2023-11-14 07:56 UTC, statkarl commented on R/dformat-checkware.R
> +    mutate(across(dato_kl_var, ~ readr::parse_datetime(.x, format = "%Y-%m-%d %H:%M:%S")))
Eg meiner me bør unngå dei, @haugedal, og har laga Trello-kort på dette for kodestilgaiden vår. Hjelpesida seier:

> A formula, e.g. ~ .x + 1. You must use .x to refer to the first argument. Only recommended if you require backward compatibility with older versions of R.

Så det er jo ei klar anbefaling.

2023-11-15 11:29 UTC, orjanls commented
Nå er anonyme funksjoner oppdatert @haugedal

2023-11-15 11:39 UTC, haugedal approved these changes

2023-11-15 11:45 UTC, merged