Haugedal/fiks regn ki univar
Rapporteket/rapwhale pull request #3
Opened 2023-08-22 10:38 UTC by haugedal

2023-08-22 12:15 UTC, statkarl requested changes
Her er mine kommentarar.

2023-08-22 12:15 UTC, statkarl commented on tests/testthat/test-ymse-funksjoner.R
> +  expect_true(all(sepal_length_resultat == sepal_length_forventa))
Her bør du vel ha `expect_identical()`?

2023-08-22 12:15 UTC, statkarl commented on tests/testthat/test-ymse-funksjoner.R
> +  expect_true(
Igjen bør det vera `expect_identical()`.

2023-08-22 12:15 UTC, statkarl commented on tests/testthat/test-ymse-funksjoner.R
> +    expected = , regn_ki_univar(numeric())
Kva gjer kommaa etter `=` her (og på dei neste linjene)?

2023-08-22 12:15 UTC, statkarl commented on R/ymse-funksjoner.R
> +regn_ki_univar = function(x, bootstrap = FALSE, alfa = 0.05, R = 9999) {
Må ha testar på dette.

2023-08-22 12:15 UTC, statkarl requested changes
Her er mine kommentarar.

2023-08-22 13:23 UTC, haugedal commented on tests/testthat/test-ymse-funksjoner.R
> +    expected = , regn_ki_univar(numeric())
Dei stamma truleg frå at eg gjekk frå éi linje, utan namn på argumenta, til fleire linjer, og fekk med eit ekstra komma. Overraskande nok fungerte koden slik han stod, med kommaa, som me såg på.

2023-08-22 13:24 UTC, haugedal commented on tests/testthat/test-ymse-funksjoner.R
> +  expect_true(all(sepal_length_resultat == sepal_length_forventa))
Einig.

2023-08-22 13:24 UTC, haugedal commented on tests/testthat/test-ymse-funksjoner.R
> +  expect_true(
Einig.

2023-08-22 13:27 UTC, haugedal commented on R/ymse-funksjoner.R
> +regn_ki_univar = function(x, bootstrap = FALSE, alfa = 0.05, R = 9999) {
La til nokre testar for bootstrapping, og éin for val av tal på replikasjonar, `R`. Kommenter gjerne viss det er fleire testar du ser behov for.

2023-08-23 07:09 UTC, statkarl requested changes
Berre ei lita endring til, så er denne klar.

2023-08-23 07:09 UTC, statkarl commented on tests/testthat/test-ymse-funksjoner.R
> +    expected = regn_ki_univar(numeric())
Er fornuftig å samanlikna med `regn_ki_univar(numeric())`, men me manglar ein test på kva `regn_ki_univar(numeric())` faktisk skal gje ut. Det minste me testar, er ein vektor med lengd 1. Så det må inn ein test på dette (gjerne i testen som står øvst i fila).

2023-08-23 07:56 UTC, haugedal commented on tests/testthat/test-ymse-funksjoner.R
> +    expected = regn_ki_univar(numeric())
Utvida den øvste testen med dette eksempelet, slik du føreslo.

2023-08-23 08:08 UTC, statkarl approved these changes
Ser bra ut.

2023-08-23 09:16 UTC, merged