forbedret prosent beskrivelse og lager tester
Rapporteket/rapwhale pull request #36
Opened 2023-11-20 14:47 UTC by orjanls

Har lagt inn beskrivelse av funksjonen `prosent`, oppdatert den anonyme funksjonen til å bruke standard R syntaks og lagt til tester.

2023-11-21 10:03 UTC, haugedal requested changes

2023-11-21 10:03 UTC, haugedal commented on R/rapporttekst-funksjoner.R
> +#' Tallene blir avrundet til `desimalar` desimalar
Når teksten er på bokmål bør «desimalar» nr. 2 vera «desimaler».

2023-11-21 10:03 UTC, haugedal commented on R/rapporttekst-funksjoner.R
> +#' hVis `desimalar` er NULL,
Stor bokstav midt i ordet `hVis`.

2023-11-21 10:03 UTC, haugedal commented on tests/testthat/test-rapporttekst-funksjoner.R
> +  expect_identical(num(numeric()), "{\\numprint{}}")
Korleis skal `num()` og  `prosent()` fungera med tomme inndata, @statkarl?

2023-11-21 10:03 UTC, haugedal commented on tests/testthat/test-rapporttekst-funksjoner.R
> +  expect_identical(prosent(numeric()), logical(0))
Korleis skal `num()` og  `prosent()` fungera med tomme inndata, @statkarl?

2023-11-21 10:09 UTC, haugedal commented
Funksjonane bør kanskje sjekka at inndata er tal, og ikkje andre ting. T.d. burde vel ikkje `num("Tekst.")` fungera, men heller gje ei feilmelding. Kan i så fall starta med å legga inn testar der inndata er andre ting enn tal.

Og kva med tal formatert som tekst (`num("12345")`), skal det gje same feilmelding?

2023-11-21 10:12 UTC, statkarl commented on R/rapporttekst-funksjoner.R
> +#' Tallene blir avrundet til `desimalar` desimalar
Blir det ikkje veldig forvirrande at namnet på argumentet er forskjellig på to nærskylde funksjonar (`num` og `prosent`)?

2023-11-21 10:14 UTC, statkarl commented on tests/testthat/test-rapporttekst-funksjoner.R
> +  expect_identical(num(numeric()), "{\\numprint{}}")
Som standard for ~alle vektorbaserte funksjonar: Utvektoren skal alltid ha same lengd som innvektoren, så tom innvektor skal gje tom utvektor (av typen tekst).

2023-11-21 10:17 UTC, statkarl commented
> Og kva med tal formatert som tekst `num("12345")`, skal det gje same feilmelding?

Viss me har ei feilmelding på alle ikkje-tal, bør det gje feilmelding, ja.

2023-11-21 10:18 UTC, statkarl commented on R/rapporttekst-funksjoner.R
> +#' Tallene blir avrundet til `desimalar` desimalar
Eg las feil. Det var berre teksten, ikkje argumentnamnet, du ville ha på bokmål, @haugedal. Då er eg einig.

2023-11-21 10:21 UTC, haugedal commented on tests/testthat/test-rapporttekst-funksjoner.R
> +  expect_identical(num(numeric()), "{\\numprint{}}")
Så då må denne testen (og så funksjonen) endrast?

2023-11-21 10:23 UTC, statkarl commented on R/rapporttekst-funksjoner.R
> +#' og `NA`-verdier blir vist som en kort tankestrek («–»).
Dette stemmer ikkje. Poenget er at ein får ut *LaTeX-kode* for formatering av talet som prosent dersom ein brukar `kvalreg`-klassen vår. Det *kan* stå forklart kva resultatet av LaTeX-koden, men det blir berre ekstrainformasjon.

2023-11-21 10:26 UTC, haugedal commented on tests/testthat/test-rapporttekst-funksjoner.R
> +  expect_identical(prosent(numeric()), logical(0))
Og denne skal då òg vera `character()`, ikkje `logical()`?

2023-11-21 10:26 UTC, statkarl requested changes

2023-11-21 10:26 UTC, statkarl commented on R/rapporttekst-funksjoner.R
> +    map_chr(\(x) num(100 * x, desimalar) |>
`map_chr()` er unødvendig her.

2023-11-21 10:28 UTC, statkarl requested changes

2023-11-21 10:28 UTC, statkarl commented on tests/testthat/test-rapporttekst-funksjoner.R
> +  expect_identical(prosent(numeric()), logical(0))
Sjå annan kommentar. Det skal vera `character()` her, ikkje `logical()`.

2023-11-21 10:30 UTC, haugedal commented
Funksjonane `num()` og `prosent()` kunne gjerne fått lagt til avsnittet `@return` i dokumentasjonen når me fyrst er i gang.

2023-11-21 10:44 UTC, statkarl commented on tests/testthat/test-rapporttekst-funksjoner.R
> +  expect_identical(num(numeric()), "{\\numprint{}}")
Ja, dei må endrast.

2023-11-21 10:46 UTC, statkarl commented on R/rapporttekst-funksjoner.R
> +#' og `NA`-verdier blir vist som en kort tankestrek («–»).
Forresten, det treng ikkje stå forklart her i det heile tatt; ein kan berre visa til hjelpefila for `num()`-funksjonen for detaljar.

2023-11-21 10:47 UTC, statkarl requested changes

2023-11-21 10:47 UTC, statkarl commented on R/rapporttekst-funksjoner.R
>  #' med' LaTeX-kommandoar for finformatert vising av tala,
Her er det ein apostrof for mykje.

2023-11-21 11:03 UTC, statkarl requested changes

2023-11-21 11:03 UTC, statkarl commented on R/rapporttekst-funksjoner.R
>    ifelse(is.na(x), "\\textendash{}", prosent_tekst)
Me brukar konsekvent `if_else()`, ikkje `ifelse()`. Førstnemnde er tryggare. (Kunne me fått ein lint-regel på slikt, @haugedal?)

2023-11-21 11:05 UTC, statkarl commented
Bør òg fiksa dei mange lintr-klagene, @orjanls.

2023-11-21 11:09 UTC, haugedal commented on R/rapporttekst-funksjoner.R
>    ifelse(is.na(x), "\\textendash{}", prosent_tekst)
Ja, det burde vel gå an å få til, @statkarl.

2023-11-21 11:33 UTC, statkarl commented
@haugedal 
> Funksjonane bør kanskje sjekka at inndata er tal, og ikkje andre ting. T.d. burde vel ikkje `num("Tekst.")` fungera, men heller gje ei feilmelding. Kan i så fall starta med å legga inn testar der inndata er andre ting enn tal.

Det vert ein ny pakkeavhengnad, men kva med å ta i bruk `checkmate`-pakken til slikt. Han verkar veldig kraftig og enkel å bruka, og han støttar mange av dei typiske testane me har for bruk for. Kan for eksempel bruka:

```r
checkmate::assert_numeric(x, finite = TRUE)
```

Sjå vignetten for eit eksempel på kor mykje han kan forenkla:
https://cran.r-project.org/web/packages/checkmate/vignettes/checkmate.html
Synspunkt, @haugedal, @orjanls, @EndreEvjen1?

2023-11-21 12:35 UTC, EndreEvjen1 commented
> Det vert ein ny pakkeavhengnad, men kva med å ta i bruk `checkmate`-pakken til slikt. Han verkar veldig kraftig og enkel å bruka, og han støttar mange av dei typiske testane me har for bruk for. Kan for eksempel bruka:
> 
> ```r
> checkmate::assert_numeric(x, finite = TRUE)
> ```
> 
> Sjå vignetten for eit eksempel på kor mykje han kan forenkla: https://cran.r-project.org/web/packages/checkmate/vignettes/checkmate.html Synspunkt, @haugedal, @orjanls, @EndreEvjen1?

Synes det ser ut som en god pakke som kan gjøre det lettere for oss, så jeg stemmer for.

2023-11-21 12:37 UTC, orjanls commented
> Sjå vignetten for eit eksempel på kor mykje han kan forenkla:
> https://cran.r-project.org/web/packages/checkmate/vignettes/checkmate.html
> Synspunkt, @haugedal, @orjanls, @EndreEvjen1?

Såg ut som en nyttig pakke som forenkler, så stemmer for `checkmate`

2023-11-21 13:04 UTC, haugedal commented
Einig i at `checkmate` ser ut som ein nyttig pakke, som både kan forenkla og gjera kode meir oversiktleg og lettlest. Stemmer for å ta han i bruk eg òg.

2023-11-23 12:15 UTC, haugedal commented on R/rapporttekst-funksjoner.R
> +#' Vektor med LaTeX-kode
Manglar punktum.

2023-11-23 12:16 UTC, haugedal commented on R/rapporttekst-funksjoner.R
> +#' og `NULL`-verdiar returnerar ein tom tekstvektor.
Det skal vera «returnerer», ikkje «returnerar».

2023-11-24 10:06 UTC, haugedal commented
> Bør òg fiksa dei mange lintr-klagene, @orjanls.

Whitespace-klagane kan enkelt fiksast ved å køyra styler på filene.

Argumenta `decimal.mark` og `big.mark` er brukt utan snake_case for å vera like argumenta i funksjonen dei vert gjeve vidare til (`scales::number_format()`). Her kan me leggja til `nolint`-kommentarar til linjene:
```
# nolint: object_name_linter
```

Del eventuelt over fleire linjer:
```
akse_tall_format = function(antall_desimaler = 2,
                            decimal.mark = ",", # nolint: object_name_linter
                            big.mark = " ", # nolint: object_name_linter
                            ...) {
```

2023-11-24 10:52 UTC, statkarl requested changes
Testane må endrast til å ikkje vera avhengig av korleis `num()` fungerer (men berre av *at* `num()` fungerer), som forklart i kommentaren.

2023-11-24 10:52 UTC, statkarl commented on tests/testthat/test-rapporttekst-funksjoner.R
> +    c("{\\numprint{12}}\\prosent", "{\\numprint{31}}\\prosent")
Her (og i andre testar) har du hardkoda at `prosent()` skal gje ut `\numprint{}`-kommandoar med formaterte talverdiar. Det står det ingenting i dokumentasjonen om, og det er langt frå sikkert at han skal gjera dette i framtida. Det er altså ein unødvendig og uheldig avhengnad til `num()` sin gjeldande funksjonalitet i testane.

(Akkurat som funksjonar skal vera mest mogleg uavhengig av *gjeldande* åtferd til andre funksjonar, gjeld det same testar. Generelt er det slik at ein funksjon berre er ansvarleg for *si eiga åtferd*, og skal berre vera avhengig av at andre funksjonar gjer jobben sin (kva denne er, er definert i dokumentasjonen), ikkje *korleis* dei gjer jobben sin. Eks. er `num()` sin jobb å gje ut ein kvalreg-klasse-kompatibel LaTeX-kommando for formatering av tal med gitt # desimalar. Om dette skjer via `\numprint{}` eller noko anna, er berre noko `num()` skal veta inni seg, og ikkje dela med andre.)

Det `prosent()` *skal* gjera, er å gje ut ein vektor der elementa er lik resultatet av `num()`, men med `\prosent` hekta på. Det er *det* testane skal testa. Dette gjer òg at du får enklare (og gjerne færre) testar.

2023-11-24 11:04 UTC, statkarl requested changes

2023-11-24 11:04 UTC, statkarl commented on tests/testthat/test-rapporttekst-funksjoner.R
> +    c("{\\numprint{12}}\\prosent", "{\\numprint{31}}\\prosent")
Ja, forresten, ein må sjølvsagt òg testa at `NA`-verdiar vert handterte rett. Altså, viss ein har ein `NA`-verdi, som `num()` no gjev ut som `–`, skal `prosent()` òg gje han ut *likt som `num()` gjer* (og altså ikkje som `–\prosent`, slik ei naiv implementering ville gitt).

2023-11-24 11:05 UTC, statkarl commented on tests/testthat/test-rapporttekst-funksjoner.R
> +    c("{\\numprint{12}}\\prosent", "{\\numprint{31}}\\prosent")
Dette må òg fungera rett viss berre *nokre* av elementa i vektoren er `NA`.

2023-11-24 11:19 UTC, statkarl commented on tests/testthat/test-rapporttekst-funksjoner.R
> +  )
Alle desse linjene/testane kan erstattast med éin test:

```r
expect_identical(
  prosent(0.1234, desimalar = 1),
  paste0(num(12.34, desimalar = 1), "\\prosent")
)
```

Det einaste ein treng testa, er altså at `desimalar`-argumentet vert rett vidaresendt til `num()`-funksjonen.

2023-11-24 11:24 UTC, statkarl requested changes
Nok eit «pass dine eigne saker»-problem.

2023-11-24 11:24 UTC, statkarl commented on tests/testthat/test-rapporttekst-funksjoner.R
> +    "Assertion on 'x' failed: Must be of type 'numeric', not 'character'."
Her *antar* du noko om korleis checkmate-funksjonen skal fungera og nøyaktig formulering av feilmeldinga. Det har du ingenting med! Det er det berre checkmate-funksjonen sjølv som skal halda orden på.

Kvar funksjonen har ansvar for si eiga åtferd. Bruk heller:

```r
checkmate::check_numeric("0.12")
```

for å få ut feilmeldinga som checkmate-funksjonen skal gje ut når inndata er tekst men skal vera numerisk (denne feilmeldinga kan godt endrast i framtidige versjonar av checkmate).

2023-11-24 11:31 UTC, statkarl requested changes
Nokre kommentarar til.

2023-11-24 11:31 UTC, statkarl commented on tests/testthat/test-rapporttekst-funksjoner.R
> +  )
Treng ikkje *to* testar som testar akkurat det same. Det held med éin.

2023-11-24 11:31 UTC, statkarl commented on tests/testthat/test-rapporttekst-funksjoner.R
> +          eksponentiell notasjon", {
Kva med små tal (som `1e-12`)?

2023-11-24 11:31 UTC, statkarl commented on tests/testthat/test-rapporttekst-funksjoner.R
> +  expect_identical(prosent(numeric()), character(0))
Denne linja kunne godt vera skilt ut som éigen test, dvs. ein test på at funksjonen handterer inndata av lengd 0. Då får ein ei meir nyttig feilmelding.

Viss ein har ei naiv implementering av funksjonen som noko slikt (som fungerer nesten alltid):

```r
paste0(num(x), "\\prosent")
````

er det forvirrande å få ei feilmelding som seier at testen «prosent() gir ut riktig verdi når kun «x»-argumentet er gitt» feila. For funksjonen *vil* jo oftast fungera når kun `x`-argumentet er oppgjeve. Det er mykje betre å få ei feilmelding som seier at testen «prosent() gir ut riktig verdi ved tom inndata» (elns.) feila.

2023-11-24 11:53 UTC, statkarl requested changes

2023-11-24 11:53 UTC, statkarl commented on R/rapporttekst-funksjoner.R
> +#' @param desimalar Kor mange desimalar som skal visast etter kommaet.
Kva tyder `NULL`-verdien for `desimalar`? (Det er jo til og med standardverdien!)

2023-11-24 12:11 UTC, statkarl commented on R/rapporttekst-funksjoner.R
> +#' @param desimalar Kor mange desimalar som skal visast etter kommaet.
Ignorerer denne kommentaren. Ser det står forklart i detaljane.

2023-11-29 11:34 UTC, haugedal approved these changes

2023-11-30 07:34 UTC, statkarl approved these changes

2023-11-30 07:36 UTC, merged